language: node_js

node_js:
  - "stable"

cache:
  directories:
  - node_modules

  env: 
    global:
      - NODE_ENV=test
      - CC_TEST_REPORTER_ID=60fce2ed1521721270adca39c16b14699ce6df4744bb37f4c814f38b73d2c9a1

script:
  - yarn test

after_script:
  - yarn coverage